
import java.sql.ResultSet;

public class dialogMateria extends javax.swing.JDialog {

    public dialogMateria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(500,450);
        this.setLocationRelativeTo(null);
        new TextPrompt("Nombre de la Materia",txtNombreMateria);
        llenarBoxNombrePlanEstudio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        boxNombrePlanEstudios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        buttonRegistrarMateria = new javax.swing.JPanel();
        labelReP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxNumeroSemestre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(43, 113, 205));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Materia");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 460, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxNombrePlanEstudios.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jPanel2.add(boxNombrePlanEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 340, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 113, 205));
        jLabel3.setText("Nombre Plan de Estudios");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 290, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 113, 205));
        jLabel2.setText("Nombre Materia:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, 40));

        txtNombreMateria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNombreMateria.setToolTipText("");
        txtNombreMateria.setBorder(null);
        txtNombreMateria.setOpaque(false);
        jPanel2.add(txtNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 240, 40));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 260, 3));

        buttonRegistrarMateria.setBackground(new java.awt.Color(255, 255, 255));
        buttonRegistrarMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonRegistrarMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonRegistrarMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegistrarMateriaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonRegistrarMateriaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRegistrarMateriaMouseEntered(evt);
            }
        });
        buttonRegistrarMateria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelReP.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        labelReP.setForeground(new java.awt.Color(43, 113, 205));
        labelReP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReP.setText("Registrar Materia");
        buttonRegistrarMateria.add(labelReP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 230, 30));

        jPanel2.add(buttonRegistrarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 240, 70));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(43, 113, 205));
        jLabel4.setText("Número del Semestre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, 40));

        boxNumeroSemestre.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        boxNumeroSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Semestre", "Segundo Semestre", "Tercer Semestre", "Cuarto Semestre", "Quinto Semestre", "Sexto Semestre", "Septimo Semestre", "Octavo Semestre", "Noveno Semestre", "Decimo Semestre" }));
        jPanel2.add(boxNumeroSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 180, 40));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 500, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarMateriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarMateriaMouseEntered
        buttonRegistrarMateria.setBackground(new java.awt.Color(43,113,205));
        labelReP.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_buttonRegistrarMateriaMouseEntered

    private void buttonRegistrarMateriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarMateriaMouseExited
        buttonRegistrarMateria.setBackground(new java.awt.Color(255,255,255));
        labelReP.setForeground(new java.awt.Color(3,113,205));
    }//GEN-LAST:event_buttonRegistrarMateriaMouseExited

    private void buttonRegistrarMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarMateriaMouseClicked
        
    }//GEN-LAST:event_buttonRegistrarMateriaMouseClicked
    
    public void llenarBoxNombrePlanEstudio(){
        boxNombrePlanEstudios.removeAllItems();
        try {
            ResultSet resultado= Splash.conexionBaseDatos.consulta("select Nombre from Plan_Estudios;");
            while(resultado.next()){
                boxNombrePlanEstudios.addItem(resultado.getString(1));
            }
        } catch (Exception e) {
            System.out.println("Error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNombrePlanEstudios;
    private javax.swing.JComboBox<String> boxNumeroSemestre;
    private javax.swing.JPanel buttonRegistrarMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelReP;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
