
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aldair
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        new TextPrompt("  Ingrese el Usuario", txtUsuario);
        new TextPrompt("  Ingrese la Contraseña", txtContraseña);
        txtUsuario.setText("root");
        txtContraseña.setText("Huevos1*");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        buttonEnter = new javax.swing.JButton();
        buttonSalir = new javax.swing.JLabel();
        buttonOcultar = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUser.setBackground(new java.awt.Color(0, 0, 0));
        labelUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelUser.setForeground(new java.awt.Color(0, 0, 0));
        labelUser.setText("USUARIO:");
        jPanel2.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 160, 40));

        labelPassword.setBackground(new java.awt.Color(0, 0, 0));
        labelPassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(0, 0, 0));
        labelPassword.setText("CONTRASEÑA:");
        jPanel2.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 210, 40));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 260, 40));

        txtContraseña.setBackground(new java.awt.Color(255, 255, 255));
        txtContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 260, 40));

        buttonEnter.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosLogin/Enter_OFF.jpg"))); // NOI18N
        buttonEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEnter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosLogin/Enter_ON.jpg"))); // NOI18N
        buttonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnterActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 130, 40));

        buttonSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosLogin/icons8_Multiply_32px.png"))); // NOI18N
        buttonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSalirMouseExited(evt);
            }
        });
        jPanel2.add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, 40));

        buttonOcultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosLogin/icons8_Expand_Arrow_32px.png"))); // NOI18N
        buttonOcultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOcultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonOcultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonOcultarMouseExited(evt);
            }
        });
        jPanel2.add(buttonOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 40, 40));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosLogin/LOGIN_CR.jpg"))); // NOI18N
        labelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelFondoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelFondoMouseMoved(evt);
            }
        });
        labelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelFondoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelFondoMouseReleased(evt);
            }
        });
        jPanel2.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnterActionPerformed
        if((txtUsuario.getText().isEmpty()) || (txtUsuario.getText() == null) || txtUsuario.getText().replace(" ","").length()==0 || (txtContraseña.getText().isEmpty()) || (txtContraseña.getText() == null) || txtContraseña.getText().replace(" ","").length()==0)
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        else if(Splash.conexionBaseDatos.ConectaBD(txtUsuario.getText(), txtContraseña.getText())){
            this.dispose();
            new InterfaceAdministrador(txtUsuario.getText()).setVisible(true);
            JOptionPane.showMessageDialog(this, "BIENVENIDO "+txtUsuario.getText());
         }
    }//GEN-LAST:event_buttonEnterActionPerformed

    private void buttonOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOcultarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_buttonOcultarMouseClicked

    private void buttonOcultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOcultarMouseEntered
        buttonOcultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
    }//GEN-LAST:event_buttonOcultarMouseEntered

    private void buttonOcultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOcultarMouseExited
        buttonOcultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
    }//GEN-LAST:event_buttonOcultarMouseExited

    private void buttonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonSalirMouseClicked

    private void buttonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalirMouseEntered
        buttonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
    }//GEN-LAST:event_buttonSalirMouseEntered

    private void buttonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalirMouseExited
        buttonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
    }//GEN-LAST:event_buttonSalirMouseExited

    private void labelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFondoMouseDragged
        this.setLocation(evt.getXOnScreen()-xx, evt.getYOnScreen()-xy);
    }//GEN-LAST:event_labelFondoMouseDragged

    int xx,xy;
    private void labelFondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFondoMouseMoved
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_labelFondoMouseMoved

    private void labelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFondoMousePressed
        labelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelFondoMousePressed

    private void labelFondoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFondoMouseReleased
        labelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_labelFondoMouseReleased

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        buttonEnter.doClick();
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        buttonEnter.doClick();
    }//GEN-LAST:event_txtUsuarioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnter;
    private javax.swing.JLabel buttonOcultar;
    private javax.swing.JLabel buttonSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
