import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class panelEditar extends javax.swing.JPanel {
    
    javax.swing.JDialog window;
    String Matricula;
    DefaultTableModel modelo;//Modelo de la tabla

    public panelEditar(javax.swing.JDialog dialog) {
        initComponents();
        setSize(990, 800);//Tamaño de el panel
        new TextPrompt(" Ingrese el Nombre del Alumno",txtNombre);
        new TextPrompt(" Ingrese el Apellido Paterno ",txtApellidoPaterno);
        new TextPrompt(" Ingrese el Apellido Materno",txtApellidoMaterno);
        new TextPrompt("   Ingrese la Matricula",txtMatricula);
        new TextPrompt("            Grupo",txtGrupo);
        window=dialog;
        window.add(this);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorNombre = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        separadorApellidoPaterno = new javax.swing.JSeparator();
        txtApellidoMaterno = new javax.swing.JTextField();
        separadorApellidoMaterno = new javax.swing.JSeparator();
        txtMatricula = new javax.swing.JTextField();
        separadorMatricula = new javax.swing.JSeparator();
        txtGrupo = new javax.swing.JTextField();
        separadorGrupo = new javax.swing.JSeparator();
        panelVerde = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonGuardarCambios = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separadorNombre.setBackground(new java.awt.Color(43, 113, 205));
        separadorNombre.setForeground(new java.awt.Color(0, 0, 0));
        separadorNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 410, 3));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 390, 50));

        txtApellidoPaterno.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtApellidoPaterno.setBorder(null);
        txtApellidoPaterno.setOpaque(false);
        txtApellidoPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPaternoMouseClicked(evt);
            }
        });
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyTyped(evt);
            }
        });
        add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 390, 50));

        separadorApellidoPaterno.setBackground(new java.awt.Color(43, 113, 205));
        separadorApellidoPaterno.setForeground(new java.awt.Color(0, 0, 0));
        separadorApellidoPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 410, 3));

        txtApellidoMaterno.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtApellidoMaterno.setBorder(null);
        txtApellidoMaterno.setOpaque(false);
        txtApellidoMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMaternoMouseClicked(evt);
            }
        });
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyTyped(evt);
            }
        });
        add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 390, 50));

        separadorApellidoMaterno.setBackground(new java.awt.Color(43, 113, 205));
        separadorApellidoMaterno.setForeground(new java.awt.Color(0, 0, 0));
        separadorApellidoMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 410, 3));

        txtMatricula.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.setBorder(null);
        txtMatricula.setOpaque(false);
        txtMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMatriculaMouseClicked(evt);
            }
        });
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyTyped(evt);
            }
        });
        add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 270, 50));

        separadorMatricula.setBackground(new java.awt.Color(43, 113, 205));
        separadorMatricula.setForeground(new java.awt.Color(0, 0, 0));
        separadorMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 280, 3));

        txtGrupo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtGrupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrupo.setBorder(null);
        txtGrupo.setOpaque(false);
        txtGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGrupoMouseClicked(evt);
            }
        });
        txtGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrupoKeyTyped(evt);
            }
        });
        add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 270, 50));

        separadorGrupo.setBackground(new java.awt.Color(43, 113, 205));
        separadorGrupo.setForeground(new java.awt.Color(0, 0, 0));
        separadorGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 280, 3));

        panelVerde.setBackground(new java.awt.Color(43, 113, 205));
        panelVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Alumno_");
        panelVerde.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 600, 60));

        add(panelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 113, 205));
        jLabel3.setText("Nombre(s):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 280, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(43, 113, 205));
        jLabel4.setText("Apellido Paterno:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(43, 113, 205));
        jLabel5.setText("Apellido Materno:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 280, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(43, 113, 205));
        jLabel6.setText("Matricula:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 280, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(43, 113, 205));
        jLabel7.setText("Grupo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 280, 40));

        buttonGuardarCambios.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        buttonGuardarCambios.setText("Guardar Cambios");
        buttonGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarCambiosActionPerformed(evt);
            }
        });
        add(buttonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 290, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarCambiosActionPerformed
        LoginInterno logInterno = new LoginInterno(null, true);
        logInterno.setVisible(true);
        if (logInterno.isLogeado()){
            if(esValidoTxt(txtNombre,separadorNombre) && esValidoTxt(txtApellidoPaterno,separadorApellidoPaterno) && esValidoTxt(txtApellidoMaterno,separadorApellidoMaterno) && esValidoTxt(txtMatricula,separadorMatricula) && esValidoTxt(txtGrupo,separadorGrupo)){
                String grupo;
                if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea editar el registro?", "Confirmar", JOptionPane.YES_NO_OPTION)==0){
                    grupo=txtGrupo.getText();
                    if (Splash.conexionBaseDatos.UpdateTableAlumno(txtMatricula.getText(),txtNombre.getText(),txtApellidoPaterno.getText(),txtApellidoMaterno.getText(),Matricula)) {
                        JOptionPane.showMessageDialog(null,"¡¡Actualizacion Exitosa!!");
                    }
                    limpiarCajas();
                    window.dispose();
                }
            }
            else{
                esValidoTxt(txtNombre, separadorNombre);
                esValidoTxt(txtApellidoPaterno, separadorApellidoPaterno);
                esValidoTxt(txtApellidoMaterno, separadorApellidoMaterno);
                esValidoTxt(txtMatricula, separadorMatricula);
                esValidoTxt(txtGrupo, separadorGrupo);
                JOptionPane.showMessageDialog(null,"Porfavor rellene todos los campos");
            }

        }
    }//GEN-LAST:event_buttonGuardarCambiosActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        limpiarTxt(separadorNombre);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoPaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPaternoMouseClicked
        limpiarTxt(separadorApellidoPaterno);
    }//GEN-LAST:event_txtApellidoPaternoMouseClicked

    private void txtApellidoMaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMaternoMouseClicked
        limpiarTxt(separadorApellidoMaterno);
    }//GEN-LAST:event_txtApellidoMaternoMouseClicked

    private void txtMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatriculaMouseClicked
        limpiarTxt(separadorMatricula);
    }//GEN-LAST:event_txtMatriculaMouseClicked

    private void txtGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGrupoMouseClicked
        limpiarTxt(separadorGrupo);
    }//GEN-LAST:event_txtGrupoMouseClicked

    private void txtMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyTyped
         validarNumerosMAT(evt);      
    }//GEN-LAST:event_txtMatriculaKeyTyped

    private void txtGrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrupoKeyTyped
        ValidarGrup(evt);
    }//GEN-LAST:event_txtGrupoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        ValidarLetras(evt,txtNombre);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyTyped
        ValidarLetras(evt,txtApellidoPaterno);
    }//GEN-LAST:event_txtApellidoPaternoKeyTyped

    private void txtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyTyped
        ValidarLetras(evt,txtApellidoMaterno);
    }//GEN-LAST:event_txtApellidoMaternoKeyTyped
    
    public boolean esValidoTxt(JTextField txtField, JSeparator separador){
        if((txtField.getText().isEmpty()) || (txtField.getText() == null) || txtField.getText().replace(" ","").length()==0){
            separador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,102,102), 5));
            return false;
        }
        else
            return true;
    }
    
    public void limpiarTxt(JSeparator separador){
        separador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
    }
    
    public void vaciarTxt(){
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtMatricula.setText("");
        txtGrupo.setText("");
        limpiarTxt(separadorNombre);
        limpiarTxt(separadorApellidoPaterno);
        limpiarTxt(separadorApellidoMaterno);
        limpiarTxt(separadorMatricula);
        limpiarTxt(separadorGrupo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGuardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelVerde;
    private javax.swing.JSeparator separadorApellidoMaterno;
    private javax.swing.JSeparator separadorApellidoPaterno;
    private javax.swing.JSeparator separadorGrupo;
    private javax.swing.JSeparator separadorMatricula;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private boolean isImpar(String grup) {
        char c=grup.charAt(0);
        System.out.println(c);
        int i=(int) c;
        if((i%2)==0)
            return false;  
       else
            return true;
            
    }

    private void limpiarCajas() {
        txtNombre.setText(null);
        txtApellidoPaterno.setText(null);
        txtApellidoMaterno.setText(null);
        txtGrupo.setText(null);
        txtMatricula.setText(null);
    }

    private boolean MatValida(String mat) {
        if(mat.trim().length()>10 || mat.trim().length()<10)
            return false;
        else
            return true;
    }

    private void validarNumerosMAT(java.awt.event.KeyEvent evt2) {
        if(txtMatricula.getText().length()<10 && (Character.isDigit(evt2.getKeyChar()))){
            txtMatricula.setText(txtMatricula.getText()+evt2.getKeyChar());
        }
        
        if(evt2.getKeyChar() == '\b' ){
            if(!txtMatricula.getText().equals(""))
                txtMatricula.setText(txtMatricula.getText());
        }
        evt2.setKeyChar((char)0);
    }

    private void ValidarGrup(java.awt.event.KeyEvent evt3) { //Método para cvalidar que el grupo sea correcto.
        if(txtGrupo.getText().length()<4 && (Character.isDigit(evt3.getKeyChar()))) //Solo se pueden Ingresar 4 números como máximo.
            txtGrupo.setText(txtGrupo.getText()+evt3.getKeyChar());
        
        
        else if((txtGrupo.getText().length()>3 || txtGrupo.getText().length()>2) &&((int)evt3.getKeyChar()==45) && (txtGrupo.getText().length()<=3 || txtGrupo.getText().length()<5)) // Si se ya se ingresaron 3 o 4 numeros se podrá poner guion bajo.
            txtGrupo.setText(txtGrupo.getText()+evt3.getKeyChar());
        
        
        else if((txtGrupo.getText().length()>4 || txtGrupo.getText().length()>3)&& (Character.isLetter(evt3.getKeyChar()))) {//Se valida que ya se puedan poner letras.
            int longi=txtGrupo.getText().length();
            if(txtGrupo.getText().charAt(longi-1)=='-') //Se obtiene el ultimo de caracter en caso de que sea "-" Se agrega la letra. Esto se hace para que solo se pueda ingresar una letra.
                txtGrupo.setText(txtGrupo.getText()+evt3.getKeyChar());
        }
        
        if(evt3.getKeyChar() == '\b' ) //Se valida si hay retroceso de carro.
            if(!txtMatricula.getText().equals(""))
                txtMatricula.setText(txtMatricula.getText());
        
        evt3.setKeyChar((char)0);
    }

    private void ValidarLetras(KeyEvent evtL,javax.swing.JTextField txtV) {
        if(Character.isLetter(evtL.getKeyChar()) || evtL.getKeyChar()==' ')
            txtV.setText(txtV.getText()+evtL.getKeyChar());
        if(evtL.getKeyChar() == '\b'){
           if(!txtV.getText().equals(""))                             
               txtV.setText(txtV.getText());                        
       }
        evtL.setKeyChar((char)0);
    }
   
    public void rellenarTxt(String Nombres,String apellidoPaterno, String apellidoMaterno,String matricula,String grupo){
        this.Matricula=matricula;
        txtNombre.setText(Nombres);
        txtApellidoPaterno.setText(apellidoPaterno);
        txtApellidoMaterno.setText(apellidoMaterno);
        txtMatricula.setText(matricula);
        txtGrupo.setText(grupo);
    }
}
