import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class panelRegistrarEmpleado extends javax.swing.JPanel {
    
    panelImportarExcel pnlImportarExcel;
    DefaultTableModel modelo;//Modelo de la tabla

    public panelRegistrarEmpleado(javax.swing.JFrame ventana) {
        initComponents();
        setSize(990, 800);//Tamaño de el panel
        new TextPrompt(" Ingrese el Nombre del Alumno",txtNombre);
        new TextPrompt(" Ingrese el Apellido Paterno ",txtApellidoPaterno);
        new TextPrompt(" Ingrese el Apellido Materno",txtApellidoMaterno);
        new TextPrompt("   Ingrese la Matricula",txtNumeroTrabajador);
        pnlImportarExcel = new panelImportarExcel();
        ventana.add(pnlImportarExcel);
        pnlImportarExcel.setLocation(230,0);
        pnlImportarExcel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorNombre = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        separadorApellidoPaterno = new javax.swing.JSeparator();
        txtApellidoMaterno = new javax.swing.JTextField();
        separadorApellidoMaterno = new javax.swing.JSeparator();
        txtNumeroTrabajador = new javax.swing.JTextField();
        separadorNumeroTrabajador = new javax.swing.JSeparator();
        panelVerde = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonRegistrar = new javax.swing.JPanel();
        labelR = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboboxtipo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separadorNombre.setBackground(new java.awt.Color(43, 113, 205));
        separadorNombre.setForeground(new java.awt.Color(0, 0, 0));
        separadorNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 410, 3));

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 390, 50));

        txtApellidoPaterno.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtApellidoPaterno.setBorder(null);
        txtApellidoPaterno.setOpaque(false);
        txtApellidoPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPaternoMouseClicked(evt);
            }
        });
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyTyped(evt);
            }
        });
        add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 390, 50));

        separadorApellidoPaterno.setBackground(new java.awt.Color(43, 113, 205));
        separadorApellidoPaterno.setForeground(new java.awt.Color(0, 0, 0));
        separadorApellidoPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 410, 3));

        txtApellidoMaterno.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtApellidoMaterno.setBorder(null);
        txtApellidoMaterno.setOpaque(false);
        txtApellidoMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMaternoMouseClicked(evt);
            }
        });
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyTyped(evt);
            }
        });
        add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 390, 50));

        separadorApellidoMaterno.setBackground(new java.awt.Color(43, 113, 205));
        separadorApellidoMaterno.setForeground(new java.awt.Color(0, 0, 0));
        separadorApellidoMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 410, 3));

        txtNumeroTrabajador.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNumeroTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroTrabajador.setBorder(null);
        txtNumeroTrabajador.setOpaque(false);
        txtNumeroTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroTrabajadorMouseClicked(evt);
            }
        });
        txtNumeroTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTrabajadorKeyTyped(evt);
            }
        });
        add(txtNumeroTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 270, 50));

        separadorNumeroTrabajador.setBackground(new java.awt.Color(43, 113, 205));
        separadorNumeroTrabajador.setForeground(new java.awt.Color(0, 0, 0));
        separadorNumeroTrabajador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
        add(separadorNumeroTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 280, 3));

        panelVerde.setBackground(new java.awt.Color(43, 113, 205));
        panelVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Trabajador");
        panelVerde.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 600, 60));

        add(panelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 113, 205));
        jLabel3.setText("Nombre(s):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 280, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(43, 113, 205));
        jLabel4.setText("Apellido Paterno:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(43, 113, 205));
        jLabel5.setText("Apellido Materno:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 280, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(43, 113, 205));
        jLabel6.setText("Número de trabajador:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 310, 40));

        buttonRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonRegistrarMouseExited(evt);
            }
        });
        buttonRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelR.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        labelR.setForeground(new java.awt.Color(43, 113, 205));
        labelR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelR.setText("Registrar");
        buttonRegistrar.add(labelR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 200, 60));

        add(buttonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 300, 80));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(43, 113, 205));
        jLabel7.setText("Número de trabajador:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 310, 40));

        comboboxtipo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        comboboxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor" }));
        add(comboboxtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 190, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        limpiarTxt(separadorNombre);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoPaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPaternoMouseClicked
        limpiarTxt(separadorApellidoPaterno);
    }//GEN-LAST:event_txtApellidoPaternoMouseClicked

    private void txtApellidoMaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMaternoMouseClicked
        limpiarTxt(separadorApellidoMaterno);
    }//GEN-LAST:event_txtApellidoMaternoMouseClicked

    private void txtNumeroTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroTrabajadorMouseClicked
        limpiarTxt(separadorNumeroTrabajador);
    }//GEN-LAST:event_txtNumeroTrabajadorMouseClicked

    private void txtNumeroTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTrabajadorKeyTyped
         validarNumerosMAT(evt);      
    }//GEN-LAST:event_txtNumeroTrabajadorKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        ValidarLetras(evt,txtNombre);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyTyped
        ValidarLetras(evt,txtApellidoPaterno);
    }//GEN-LAST:event_txtApellidoPaternoKeyTyped

    private void txtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyTyped
        ValidarLetras(evt,txtApellidoMaterno);
    }//GEN-LAST:event_txtApellidoMaternoKeyTyped

    private void buttonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarMouseClicked
        
            if(esValidoTxt(txtNombre,separadorNombre) && esValidoTxt(txtApellidoPaterno,separadorApellidoPaterno) && esValidoTxt(txtApellidoMaterno,separadorApellidoMaterno) && esValidoTxt(txtNumeroTrabajador,separadorNumeroTrabajador)){
            if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea registrar este Empleado?", "Confirmar", JOptionPane.YES_NO_OPTION)==0){
                if(MatValida(txtNumeroTrabajador.getText())){
                    try {
                          //Splash.conexionBaseDatos.InsertTableAlumno(txtMatricula.getText(),txtNombre.getText(),txtApellidoPaterno.getText(),txtApellidoMaterno.getText());
                          String resul=Splash.conexionBaseDatos.CallProcEmple(txtNumeroTrabajador.getText(),txtNombre.getText(),txtApellidoPaterno.getText(),txtApellidoMaterno.getText(), (String) comboboxtipo.getSelectedItem());
                          if(resul!=null)
                             if(Integer.parseInt(resul)==1062)
                              JOptionPane.showMessageDialog(null,"Ya existe un Empleado con ese Identificador");
                       
                    } catch (SQLException ex) {
                        Logger.getLogger(panelRegistrar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(null,"Registro Exitoso");
                    limpiarCajas();
                }
                else
                    JOptionPane.showMessageDialog(null,"El numero de trabajador no es valido");
            }
        }
        else{
            esValidoTxt(txtNombre, separadorNombre);
            esValidoTxt(txtApellidoPaterno, separadorApellidoPaterno);
            esValidoTxt(txtApellidoMaterno, separadorApellidoMaterno);
            esValidoTxt(txtNumeroTrabajador, separadorNumeroTrabajador);
            JOptionPane.showMessageDialog(null,"Porfavor rellene todos los campos");
        }
    }//GEN-LAST:event_buttonRegistrarMouseClicked

    private void buttonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarMouseEntered
        buttonRegistrar.setBackground(new java.awt.Color(43,113,205));
        labelR.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_buttonRegistrarMouseEntered

    private void buttonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarMouseExited
        buttonRegistrar.setBackground(new java.awt.Color(255,255,255));
        labelR.setForeground(new java.awt.Color(43,113,205));

    }//GEN-LAST:event_buttonRegistrarMouseExited
    
    public boolean esValidoTxt(JTextField txtField, JSeparator separador){
        if((txtField.getText().isEmpty()) || (txtField.getText() == null) || txtField.getText().replace(" ","").length()==0){
            separador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,102,102), 5));
            return false;
        }
        else
            return true;
    }
    
    public void limpiarTxt(JSeparator separador){
        separador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 113, 205), 5));
    }
    
    public void vaciarTxt(){
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtNumeroTrabajador.setText("");
        limpiarTxt(separadorNombre);
        limpiarTxt(separadorApellidoPaterno);
        limpiarTxt(separadorApellidoMaterno);
        limpiarTxt(separadorNumeroTrabajador);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonRegistrar;
    private javax.swing.JComboBox<String> comboboxtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelR;
    private javax.swing.JPanel panelVerde;
    private javax.swing.JSeparator separadorApellidoMaterno;
    private javax.swing.JSeparator separadorApellidoPaterno;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorNumeroTrabajador;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroTrabajador;
    // End of variables declaration//GEN-END:variables

    private void limpiarCajas() {
        txtNombre.setText(null);
        txtApellidoPaterno.setText(null);
        txtApellidoMaterno.setText(null);
        txtNumeroTrabajador.setText(null);
    }

    private boolean MatValida(String mat) {
        if(mat.trim().length()>10 || mat.trim().length()<10)
            return false;
        else
            return true;
    }

    private void validarNumerosMAT(java.awt.event.KeyEvent evt2) {
        if(txtNumeroTrabajador.getText().length()<10 && (Character.isDigit(evt2.getKeyChar()))){
            txtNumeroTrabajador.setText(txtNumeroTrabajador.getText()+evt2.getKeyChar());
        }
        
        if(evt2.getKeyChar() == '\b' ){
            if(!txtNumeroTrabajador.getText().equals(""))
                txtNumeroTrabajador.setText(txtNumeroTrabajador.getText());
        }
        evt2.setKeyChar((char)0);
    }
    
    private void ValidarLetras(KeyEvent evtL,javax.swing.JTextField txtV) {
        if(Character.isLetter(evtL.getKeyChar()) || evtL.getKeyChar()==' ')
            txtV.setText(txtV.getText()+evtL.getKeyChar());
        if(evtL.getKeyChar() == '\b'){
           if(!txtV.getText().equals(""))                             
               txtV.setText(txtV.getText());                        
       }
        evtL.setKeyChar((char)0);
    }
   
}
